# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCapitulo', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField()),
                ('capa', models.ImageField(default='capitulo_capas/None/no-img.jpg', upload_to='capitulo_capas/')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeObra', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=500)),
                ('ativada', models.BooleanField()),
                ('capa', models.ImageField(default='obra_capas/None/no-img.jpg', upload_to='obra_capas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.ImageField(default='paginas/None/no-img.jpg', upload_to='paginas/')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obra'),
        ),
    ]
